### ISSUE TITLE
Add Wifi Code to the ROOM display

### ISSUE THREAD

**Issue by samueljon** [opinkerfi/MeetEasier#3]
**Branch: opinkerfi**
Add wifi QR code support to room display in sidebar.js

Create React component f.ex. <Wifi ....>

WIP: example markup as a initial starting point to add to sidebar.js:
 ```html
    <div id="single-room__wifi">
      <div id="single-room__wifi-title">
        <h2>{config.wifiTitle}</h2>
      </div>
      <div id="single-room__wifi-logo">
      <img id="single-room__wifi-image" src="/svgs/wi-fi.svg" alt="Wifi" />  
      </div>
      
      <div id="single-room__wifi-text">
        <p>Wifi: wifi-name</p>
        <p>Password: password</p>
      </div>
      <img id="single-room__wifi-image" src="/wifi.png" alt="Wifi Code" />
    </div>
```

WIP: Initial SCSS as a starting point into global.scss:
```SCSS
    #single-room__wifi {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      width: 30%;
      position: absolute;
      bottom: 8px;
      right: 16px;
    }
    #single-room__wifi-title {
      
      text-transform: uppercase;
      text-align: center;
      font-size: 1.8vw;
      font-weight: lighter;
      width: 100%;
    }

    #single-room__wifi-text {
      display: inline-block;
      flex: 1;
      padding-left: 2em;
    }
    #single-room__wifi-image {
      display: inline-block;
      flex: 1;
      max-height: 100px;
      max-width: 100px;
      align-content: flex-start;
    }
```

<img width="1387" alt="wificode" src="https://user-images.githubusercontent.com/178840/72108178-e31a0e00-332a-11ea-8e7e-9345f9ff218f.png">
